#!/usr/bin/env node
/**
 * Refresh components/fan/images.ts with the latest editorial photos
 * from revolutionsoccer.net.
 *
 * Two modes:
 *   - Firecrawl (preferred): set FIRECRAWL_API_KEY (get one at firecrawl.dev)
 *     and run `npm run fetch:images`. Handles JS-rendered pages reliably.
 *   - curl fallback: if no API key is set, falls back to a static `curl`
 *     of the homepage HTML. Works for static markup; misses anything
 *     hydrated client-side.
 *
 * The script PRINTS the suggested URL set to stdout and writes a backup
 * `images.ts.next` next to the original — it does NOT overwrite the active
 * file. Review the diff, then `mv components/fan/images.ts.next components/fan/images.ts`.
 */
import { promises as fs } from "node:fs";
import path from "node:path";

const PAGES = [
  "https://www.revolutionsoccer.net",
  "https://www.revolutionsoccer.net/schedule",
  "https://www.revolutionsoccer.net/news",
];

const RX = /https:\/\/images\.mlssoccer\.com\/image\/[^"'\s]+\.(jpg|jpeg|png|webp)/gi;

async function viaFirecrawl(apiKey) {
  const results = [];
  for (const url of PAGES) {
    const res = await fetch("https://api.firecrawl.dev/v2/scrape", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        url,
        formats: ["html"],
        onlyMainContent: false,
        waitFor: 2000,
      }),
    });
    if (!res.ok) {
      throw new Error(`Firecrawl ${res.status} on ${url}: ${await res.text()}`);
    }
    const json = await res.json();
    const html = json?.data?.html ?? json?.html ?? "";
    results.push(...(html.match(RX) ?? []));
  }
  return results;
}

async function viaCurl() {
  const results = [];
  for (const url of PAGES) {
    const res = await fetch(url, {
      headers: { "User-Agent": "Mozilla/5.0 (class-project-demo)" },
    });
    const html = await res.text();
    results.push(...(html.match(RX) ?? []));
  }
  return results;
}

function classify(url) {
  if (url.includes("editorial_landscape")) return "EDITORIAL";
  if (url.includes("keep-aspect-ratio")) return "BANNER";
  if (url.includes("logo") || url.includes("Logo")) return "LOGO";
  if (url.includes("sponsor")) return "SPONSOR";
  if (url.includes("match-icons")) return "ICON";
  return "OTHER";
}

async function main() {
  const apiKey = process.env.FIRECRAWL_API_KEY;
  let urls;
  if (apiKey) {
    console.log("→ Firecrawl mode (FIRECRAWL_API_KEY set)");
    urls = await viaFirecrawl(apiKey);
  } else {
    console.log(
      "→ curl fallback (set FIRECRAWL_API_KEY for Firecrawl-quality JS-rendered scrapes)",
    );
    urls = await viaCurl();
  }
  const unique = [...new Set(urls)];

  // Drop responsive srcset variants and logos/sponsors — keep just editorials
  // and banners that look usable in the demo.
  const usable = unique.filter((u) => {
    const k = classify(u);
    return k === "EDITORIAL" || k === "BANNER";
  });

  console.log(`Found ${unique.length} candidate image URLs (${usable.length} usable).`);
  for (const u of usable.slice(0, 20)) console.log("  ", classify(u).padEnd(10), u);

  const out = `// Auto-generated by scripts/fetch-images.mjs — review before promoting
// to components/fan/images.ts. Source: revolutionsoccer.net via Firecrawl/curl.

export const SCRAPED = ${JSON.stringify(usable, null, 2)};
`;
  const target = path.join(process.cwd(), "components/fan/images.ts.next");
  await fs.writeFile(target, out, "utf8");
  console.log(`\nWrote ${target} — review then promote.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
